[chisel]
src.manual = "f347914dee389cebbe48ac4ef2e350e5ac1d267a"
fetch.github = "chipsalliance/chisel"

[chisel-interface]
src.git = "https://github.com/chipsalliance/chisel-interface"
src.branch = "sdram"
fetch.github = "chipsalliance/chisel-interface"
